Fix nightly deployment hopefully for the last time

diff --git a/.github/workflows/NightlyDeploy.yml b/.github/workflows/NightlyDeploy.yml
--- a/.github/workflows/NightlyDeploy.yml
+++ b/.github/workflows/NightlyDeploy.yml
@@ -37,13 +37,13 @@ jobs:
           fetch-depth: 100
       - name: Check changes
         run: |
-          git diff @{24.hours.ago}..HEAD --name-only
-          if ! git diff @{24.hours.ago}..HEAD --name-only | grep -E '^((Dialog)|(Manual)|(Menu)|(Module)|(Other)|(StringTable)|(System)|(VersionInfo)|(240)\/)'; then
-            echo "No files translated. Won't making new release."
-            echo ::set-env name=RC_CHANGED::0
+          FROM_COMMIT=$(git rev-list origin/master@{yesterday} --before 24.hours.ago | tail -n1)
+          git diff $FROM_COMMIT..HEAD --name-only
+          if ! git diff $FROM_COMMIT..HEAD --name-only | grep -E '^((Dialog)|(Manual)|(Menu)|(Module)|(Other)|(StringTable)|(System)|(VersionInfo)|(240)\/)'; then
+            echo "No files translated. Aborting!"
+            exit 1
           else
-            echo "Some files translated. Will making new release."
-            echo ::set-env name=RC_CHANGED::1
+            echo "Some files translated. Continuing."
           fi
       - name: Set enviroment variables
         # run: |
@@ -147,7 +147,6 @@ jobs:
           name: Domino_Translated_v${{env.VERSION_NUM}}-nightly.${{env.BUILD_DATE}}.exe
           path: Domino_Translated.exe
       - name: Write release body
-        if: env.RC_CHANGED == true
         # run: |
         #   echo "\
         #   ### Release Notes
@@ -196,7 +195,6 @@ jobs:
           *Built on ${{env.BUILD_DATE_FULL}}.*
           *Commits listed are the ones that translated some files.*" >> release.txt
       - name: Create release
-        if: env.RC_CHANGED == true
         uses: softprops/action-gh-release@v1
         env:
           GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
